name: ic_upstream3RealValues
number: 3
model_path: '../../../outputs/transfer-learning-experiment/mlp-ic_upstream3_Imputation_Real_Values/model_best.pth'
normalizer_path: '../../../data/ic_upstream3_Imputation_Real_Values_exp_100_1/normalizer.pkl'
imputationMethod: RealValues

model:
  name: mlp
  dropout: 0.09581744743753569
  d_embedding: 240
  d_layers:
    - 484
    - 408
    - 408
    - 408
    - 408
    - 206
  use_mlp_head: false
  freeze_feature_extractor: false
  model_path:

hyp:
  epochs: 200
  lr: 0.0008378802782692501
  lr_decay: step
  lr_factor: 0.1
  lr_schedule:
    - 40
    - 80
  optimizer: adam
  patience: 30
  save_period: 100000000.0
  seed: 0
  test_batch_size: 256
  train_batch_size: 256
  use_patience: true
  val_period: 10
  warmup_period: 5
  weight_decay: 3.553234259720536e-05
  momentum: 0.9
  warmup_type: linear
  head_warmup_period: 10
  head_lr: 0.001
  plateau_stop: true
  plateau_patience: 5
  plateau_min_epochs: 75
  plateau_window: 30
  plateau_ema_span: 10
  plateau_min_rel_improvement: 1e-3
  plateau_slope_significance_threshold: 1
  plateau_require_negative_slope_to_stop: false
