name: ic_upstream3Mean
number: 3
model_path: '../../../outputs/transfer-learning-experiment/mlp-ic_upstream3_Imputation_Mean_exp_100_1/model_best.pth'
normalizer_path: '../../../data/ic_upstream3_Imputation_Mean_exp_100_1/normalizer.pkl'
imputationMethod: Mean
model:
  name: mlp
  d_embedding: 280
  model_path:
  use_mlp_head: false
  freeze_feature_extractor: false
  dropout: 0.1
  d_layers: [442, 426, 426, 426, 426, 426, 227]
hyp:
  epochs: 200
  lr: 0.0007685784854188046
  lr_decay: step
  lr_factor: 0.1
  lr_schedule:
    - 40
    - 80
  optimizer: adam
  patience: 30
  save_period: 100000000.0
  seed: 0
  test_batch_size: 256
  train_batch_size: 256
  use_patience: true
  val_period: 10
  warmup_period: 5
  weight_decay: 4.1583284470012104e-06
  momentum: 0.9
  warmup_type: linear
  head_warmup_period: 10
  head_lr: 0.001
  plateau_stop: true
  plateau_patience: 20
  plateau_min_epochs: 50
  plateau_slope_threshold: 0.00005