name: ic_upstream4GroundTruth
number: 4
model_path: '../../../outputs/transfer-learning-experiment/mlp-ic_upstream4_Imputation_Ground_Truth_exp_100_1/model_best.pth'
normalizer_path: '../../../data/ic_upstream4_Imputation_Ground_Truth_exp_100_1/normalizer.pkl'
imputationMethod: Ground_Truth

model:
  name: mlp
  d_embedding: 344
  model_path:
  use_mlp_head: false
  freeze_feature_extractor: false
  d_layers: [11, 390, 390, 390, 390, 390, 390, 285]
  dropout: 0.1462845565618281

hyp:
  epochs: 200
  lr: 0.0008012524146278996
  lr_decay: step
  lr_factor: 0.1
  lr_schedule:
    - 40
    - 80
  optimizer: adam
  patience: 30
  save_period: 100000000.0
  seed: 0
  test_batch_size: 256
  train_batch_size: 256
  use_patience: true
  val_period: 10
  warmup_period: 5
  weight_decay: 0.00016786533488000316
  momentum: 0.9
  warmup_type: linear
  head_warmup_period: 10
  head_lr: 0.001

  plateau_stop: false
  plateau_patience: 5
  plateau_min_epochs: 75
  plateau_window: 30
  plateau_ema_span: 10
  plateau_min_rel_improvement: 1e-3
  plateau_slope_significance_threshold: 1
  plateau_require_negative_slope_to_stop: false