name: ic_upstream2Gaus
number: 2
model_path: '../../../outputs/transfer-learning-experiment/mlp-ic_upstream2_Imputation_Gaussian_exp_100_1/model_best.pth'
normalizer_path: '../../../data/ic_upstream2_Imputation_Gaussian_exp_100_1/normalizer.pkl'
imputationMethod: Gaussian
model:
  name: mlp
  d_embedding: 120
  model_path:
  use_mlp_head: false
  freeze_feature_extractor: false
  dropout: 0.1
  d_layers: [179, 160, 145]
hyp:
  epochs: 200
  lr: 0.0007428238479534785
  lr_decay: step
  lr_factor: 0.1
  lr_schedule:
    - 40
    - 80
  optimizer: adam
  patience: 30
  save_period: 100000000.0
  seed: 0
  test_batch_size: 256
  train_batch_size: 256
  use_patience: true
  val_period: 10
  warmup_period: 5
  weight_decay: 0.0004997757090832181
  momentum: 0.9
  warmup_type: linear
  head_warmup_period: 10
  head_lr: 0.001
  plateau_stop: true
  plateau_patience: 15
