name: ic_upstream4Mean
number: 4
model_path: '../../../outputs/transfer-learning-experiment/mlp-ic_upstream4_Imputation_Mean_exp_100_1/model_best.pth'
normalizer_path: '../../../data/ic_upstream4_Imputation_Mean_exp_100_1/normalizer.pkl'
imputationMethod: Mean
model:
  name: mlp
  d_embedding: 144
  model_path:
  use_mlp_head: false
  freeze_feature_extractor: false
  d_layers: [57, 364, 364, 364, 364, 489]
hyp:
  epochs: 200
  lr: 0.0004911362148772127
  lr_decay: step
  lr_factor: 0.1
  lr_schedule:
    - 40
    - 80
  optimizer: adam
  patience: 30
  save_period: 100000000.0
  seed: 0
  test_batch_size: 256
  train_batch_size: 256
  use_patience: true
  val_period: 10
  warmup_period: 5
  weight_decay: 0.0001425952894416582
  momentum: 0.9
  warmup_type: linear
  head_warmup_period: 10
  head_lr: 0.001
