name: ic_downstream1_upstream4
source: local
task: multiVariantRegression
normalization: quantile
normalizer_path: '../../../data/ic_downstream1_upstream4/normalizer.pkl'
stage: 'pretrain'
y_policy: 'mean_std'
