name: ic_upstream2_ImputacaoEstatistica_exp_100_1
source: local
task: regression
normalization: quantile
normalizer_path: '../../../data/ic_upstream2_ImputacaoEstatistica_exp_100_1/normalizer.pkl'
stage: 'pretrain'
y_policy: 'mean_std'
