name: ic_upstream4_Imputation_Real_Values_exp_100_1
source: local
task: regression
normalization: quantile
normalizer_path: '../../../data/ic_upstream4_Imputation_Real_Values_exp_100_1/normalizer.pkl'
stage: 'pretrain'
y_policy: ''
